model: 'MaskModelV2'
task_name: "mask_classification"
ckpt_path: './checkpoints'
seed: 42
data:
  train_dir: "./data/train/images"
  csv_dir: "./data/train/train.csv"
  valid_rate: 0.2
  image_size: 380
train:
  batch_size: 32
  lr: 0.001
  epoch: 25
