task_name: "mask_classification"
ckpt_path: '/data/ephemeral/home/teamcode/level1-imageclassification-cv-07/checkpoints/tf_efficientnet_b4_ns_mask_singlelabel/v4/4-0.9807-0.86.pth'
seed: 42
data:
  csv_dir: "/data/ephemeral/home/eval/info.csv"
  test_dir: "/data/ephemeral/home/eval/images"
  image_size: '512, 384'
