task_name: "mask_classification"
seed: 42
model: 'tf_efficientnet_b4_ns'
ckpt_path: './checkpoints'

fast_train_mode: False

data:
  train_dir: "/data/ephemeral/home/seg_data/train/images"
  csv_dir: "/data/ephemeral/home/seg_data/train/train.csv"
  valid_rate: 0.2
  image_size: '512, 384'

train:
  loss: 'focal'
  optim: 'adamw'
  batch_size: 32
  lr: 0.0001
  epoch: 25
  imagenet: False
  early_patience: 5
  mix: 'mixup'
  log_interval: 50
