task_name: "mask_classification"
seed: 42
model: 'mobilevitv2_200.cvnets_in22k_ft_in1k_384'
ckpt_path: './checkpoints'

fast_train_mode: False

data:
  train_dir: "/data/ephemeral/home/train/images"
  csv_dir: "/data/ephemeral/home/train/train.csv"
  valid_rate: 0.2
  image_size: '512, 384'

train:
  loss: 'f1'
  optim: 'adamw'
  batch_size: 16
  lr: 0.0001
  epoch: 25
  imagenet: False
  early_patience: 5
  mix: 'mixup'
  log_interval: 50
